### ISSUE TITLE
DTB size increase results in non-bootable/invalid DTB seen by the kernel

### ISSUE THREAD

**Issue by ffainelli** [zonque/pxa-impedance-matcher#3]
On BCM63138, after making some changes to the DTB, its size increased from 4.0K to 4.5K, and that results in the kernel seeing a completely invalid DTB, browsing it through /proc/device-tree, it really seems is corrupted and contains garbage.

I have not been able to track down yet what is wrong, the alignments look okay, does that ring any bell? Are there any obvious parts that could be overwritten?

**Comment by zonque** [comment]
It could be related to the kernel overwriting the DTB location during uncompression. Does something like the below help?

  https://github.com/raumfeld/linux-am33xx/commit/1dd5807e0

**Comment by ffainelli** [comment]
It does not really help no, but thanks for the patch. It really seems like it's being overwritten, because we boot with the proper compatible string, and the very early nodes (clocks, cpu, l2 cache etc.) are obviously corrupted or missing. I will keep digging further, might be worth placing the DTB at a known good location where it is not going to be overwritten later on.

**Comment by zonque** [comment]
If it is overwritten, the decompressor is likely the culprit. Where to put the DTB in memory is of course platform specific, but if you know your memory map, I'd just put it somewhere way outside the danger zone and see if that helps.

**Comment by zonque** [comment]
BTW, could you check if this still happens with v1? Chances are I fixed this recently.

**Comment by ffainelli** [comment]
Yes, let me see if I can dig the reference board I was using, give me a couple of days, thanks Daniel!

**Comment by ffainelli** [comment]
I was able to dig up the board and get it into a booting state, let me experiment a bit with making changes to DTB before declaring this a victory, but it would appear that your RELOCATE_DTB changes do indeed help. FWIW, I am putting the DTB at 64MB in RAM (RAM is mapped at PA 0x0) and that appears to work nicely.

**Comment by ffainelli** [comment]
No longer a problem with the relocation code. Thanks Daniel!
